proglangdesign/proglangdesign.github.io

index.html
Here it is.  
As I wrote on IRC, it tried to get this clean, so the html looks correct and they are no trainling spaces.
-----------
VIM complains on a few things at the and of the page.
One is about the`<tt>` flag, which is said to have been removed from html5, but I don't think this is a real issue.
But on the *egelbot* [entry](https://github.com/fennecdjay/proglangdesign.github.io/blob/master/index.html#L213), there are a few problems related to the `<dt>` flag. Shall I fix it?
=> Add fennecdjay/Gwion

index.html
While the site apparently accepts additions of users and projects who aren't regulars on the IRC channel, it is still very focused on the IRC channel. Many users have been congregating on the discord chat and other users are on only the subreddit. This change makes the site more inclusive of those parts of the community.
Changes:
* Page title and header changed from "#proglangdesign" to "Programming Language Design"
* Update description under "People and Projects" to be inclusive
* Added "Join Us!" section to top right with links to IRC, discord, and subreddit. Thus making it clear that all three are part of the community.
* Removed the subreddit from handy links since it now appears in the join us section
* Moved "Wiki" section above "Joining the GitHub organization" because it seemed …
=> Make the site more inclusive of the Discord and Subreddit communities

index.xhtml
I noticed I was "Boney" under one entry, and "PaulBone" under another.
I've changed this to "Paul Bone" and given my website's URL for both.  I
also tweaked the description of Plasma and deemphasised my work on
Mercury (it previously looked like I was a founder, I was not).
=> Use my name rather than inconsistent aliases

index.xhtml, style.css
Opening for discussion. 
Changes headers to pure black and page text to #333, so that links are visually distinguishable from headers, while headers still stand out from normal text.
Coincidentally also changes the `$ proglangdesign` in the page header to be a link to the root page, as it's a common web idiom and usually is the case on websites.
=> Change header color to black

index.xhtml
I don't expect this will be at all controversial. It establishes that `https://www.proglangdesign.net/` is the canonical URL, not `https://www.proglangdesign.net/index.xhtml`.
=> Add canonical URL for main page

index.xhtml
This makes the wiki link lead to the wiki, and adds a new link that
leads to where the wiki can be edited on github.
=> Update links to wiki

_data/projects.yml
This pull request would add in the Horse64 language I am working on. Please note I referenced the logo via URL rather than adding it in on purpose, since it's licensing doesn't match the MIT license in this repository, and I also find it advantageous that it'll automatically stay up-to-date.
=> Adding in Horse64 with logo URL-referenced (since it's not MIT-licensed)

_data/projects.yml
I accidentally added in the logo variant that looks really poorly scaled down :eyes: :scream: even though I have one that works nicely in smaller spaces. So I apologize for yet another pull request, but this one changes the Horse64 logo URL accordingly such that it looks nicer in the  `proglangdesign.net` listing
=> Update Horse64 entry to use small-space compatible one

_data/projects.yml
Updating Horse64's text since my previous summary could have been read as a slight stab on Python, which doesn't feel like a useful thing to do in retrospect. I think this new text makes it more obvious it's a different spin on a Python-alike while hopefully no longer possibly suggesting Python as somehow comparatively worse.
=> Update Horse64 text to be less potentially negative on Python

index.xhtml
Since bots speaking languages off the project are welcome (see #103), gwionbot is now live on proglangdesign.
This PR adds a reference to this bot, in the dedicated place.
---
I don't know if the issue has to be closed, so I let it open now, other languages devs might find the info interresting.
=> Add gwionbot reference

_data/projects.yml
I accidentally put `image` instead of `icon`
=> Fix Calypso's icon

_data/projects.yml
Update Github link for `Firefly` language.
Link at [projects.yml](https://github.com/proglangdesign/proglangdesign.github.io/blob/master/_data/projects.yml#L145) was broken. It redirected to `https://github.com/https://github.com/Ahnfelt/firefly-boot` instead of `https://github.com/Ahnfelt/firefly-boot`. I fixed it
=> Fix link to Firefly github

_data/projects.yml
Fixed a typo in the summary of Lapla and removed the link to it's Github repository
=> Fixed typo and removed link to Github repository

_data/projects.yml
The link for the `Chaos`-language (https://chaos-lang.org/) currently links to a casino site? This probably wasn't always the case, but it seems to be now. A member of the discord server noticed this, so I hereby suggest removing the link.
=> Update the link for `Chaos`

_data/projects.yml
Change the Gera website link from the Github organization to the actual Gera website
=> Change Gera website link

_data/projects.yml
The language previously named Moose64 has been renamed to Horse64 Root to make it more clear that it is a sibling project that ties into the same ecosystem. I adjusted the data accordingly.
=> Adjust data for the renaming of Moose64 to Horse64 Root

_data/projects.yml, _data/tags.yml
This adds some more details to the Horse64 and Horse64 Root list entries, including the new "garbage collection" tag which I imagine will be useful for many other langs to use as well.
=> Add details to Horse64 and Horse64 Root, including new "garbage collection" tag

_data/projects.yml
In https://github.com/proglangdesign/proglangdesign.github.io/pull/219 I introduced a syntax error without noticing. This change fixes the syntax error.
=> Fix syntax error in projects.yml

_data/tags.yml
In https://github.com/proglangdesign/proglangdesign.github.io/pull/219 I put "dynamic types" for some languages since it's the natural opposite to "static types" and mentioned in the descriptions, but I forgot to add it to the tags list. Sorry about that.
Alternatively, I could also remove the "dynamic types" entries again if that is preferred.
=> Add dynamic types to tags.yml

_data/projects.yml
This adds the "garbage collection" tag for the langs where I managed to hunt down some confirmation on their websites that they use garbage collection. Most likely, many other languages offer garbage collection as well, but I didn't want to guess and to categorize anything incorrectly.
=> Add "garbage collection" tag for the langs where I found confirmation

index.html
I noticed that language names with a space character break the markup by leading to a broken element id. This change attempts to mitigate the problem.
=> Try to fix markup issues caused by space characters in language names

_data/projects.yml, css/style.css, index.html, static/filter.js
I made an attempt to be able to mark projects as inactive via `inactive: yes`.
This commit includes a short description of what I think makes most sense as inactive (which is no commits for more than two years, or website dead with no commits in recent months), and I reworked the website template to hopefully show these inactive projects separately so that active projects get shown more prominently. The inactive list is way less detailed so that it remains easier to maintain, since it needs a separate section in the template handling. A project can be easily moved back to active by simply removing the `inactive: yes` data entry again.
I don't really know if this will work without major bugs on the live website. But I guess the best test would be to simply merge it and try it out, or is …
=> An attempt to be able to move inactive projects into a separate section (feedback wanted if this is a good idea!)

css/style.css
This adds an optional dark mode to the CSS, depending on the user's dark mode style settings, so that the page is less extreme to look at for dark mode users. For users that don't use dark mode, nothing should be changed.
=> Try adding an optional dark mode for all the dark mode users

css/style.css
The title of the sub section was a little distracting, so I toned down the intensity. This uses opacity instead of overriding the color, so that the text color of custom themes will be preserved.
=> Fix small tag info heading to be less annoying

_data/tags.yml
I've often seen discussions what is a scripting language and what isn't, and probably most languages can be "misused" for scripting tasks even if not intended for that. So I figured perhaps it makes most sense if it's decided by the people making the language if that is it's purpose? And that it might make sense to put that as a tag description, as guidance for people adding their languages to the list in the future.
Any other suggestions or protest welcome.
=> Add a tag description proposal for the scripting tag
