proglangdesign/proglangdesign.github.io

- index.html
- Added the Dyvil programming language (https://github.com/dyvil/dyvil) to the Index.
> Add Dyvil to index

- index.html
Updated to reflect namechange from some time ago, and fix alphabetical order
> fix names and ordering

- .editorconfig
This adds a .editorconfig file that matches the existing style of the files. I've separated this from any other work because I think this is handy regardless.
> Add editor config matching existing style

- index.html
> wee language

- style.css
Opening for discussion as well.
Adds a subtle fun touch from the earlier redesign discussions missing in the final design: a trailing underscore which blinks every five seconds.
> Add blinking underscore to $ proglangdesign.net_

- style.css
> Make blink time consistent with actual cursor

- style.css
Now that I look at it, I think we should make it blink slightly slower so it is not distracting.
> Make blink time a little less intrusive

- index.xhtml
- style.css
Created a footer element that is dismissible and stays on bottom of page.
> Added GitHub edit link to footer

- index.xhtml
as spelled at http://craftinginterpreters.com/ or http://gameprogrammingpatterns.com/
> Bob's name spelling

- index.xhtml
> Fix typo in URL.

- index.xhtml
A pragmatic, readable and efficient programming language for technical applications.
> Change Bee Description

- _data/projects.yml
I have changed the goals of my language
> Update summary and website for Alox

- index.xhtml
Hello,
This tiny PR will fix : 
- 1 typo in `index.xhtml`
Ciao! :robot:
> Fix typo in index.xhtml

- _data/projects.yml
Star has its own channel on the Discord server, so I figured it wouldn't hurt to add it here too.
> Add info about the Star programming language

- _data/projects.yml
Unlike Star, we don't have any discord channel or something, but I figured that it won't hurt if I add it here. Also, this is actually the first case of authors being used =)
> Add info about ForthScript programming language

- index.xhtml
As stated on the IRC, linking bots to their sources would be nice addition.
This PR does just that.
> Add sources for bots

- _data/projects.yml
> Removed xenon

- _data/projects.yml
Trying to move away from the whole Objective-C thing since it led to some misconceptions about the language
> Update Star's language summary

- _data/projects.yml
> Update Calypso tagline

- _data/projects.yml
> Update MANOOL tagline

- _data/projects.yml
- images/lang/star.svg
Dunno if the whitespace trimming is an issue but vscode kept doing it even when I turned the setting off
> Add logo for Star

- _data/projects.yml
I added the Sugi programming language to the list.
> projects.yml update

- _data/projects.yml
I do not know if my programming language is good enough to qualify here.
> Added the AEC programming language to the data.

- _data/projects.yml
Adds Mlatu programming language
> Add Mlatu language

- _data/projects.yml
> Add Discord link for Butter

- _data/projects.yml
Lesma was inactive for a few years, but now it has a brand new compiler and documentation has moved around.
> Update Lesma info

- _data/projects.yml
New website for Argon and description update
> Update Argon info

- _data/projects.yml
Add general information about the Lapla programming language, including the future Github-repository, Discord-server, author and description.
> Add the Lapla programming language

- _data/projects.yml
(sorry, I just discovered this tag existed)
> added a discord link for snowball

- _data/projects.yml
Add the website link for Lapla
> Add Lapla website

- _data/projects.yml
As the Lapla project was killed by yours truly some time ago, it is hereby removed.
> Removed Lapla from projects.yml

- _data/projects.yml
Remove archived outdated repo link for Horse64 and update logo path
> Update projects.yml for Horse64

- _data/projects.yml
This  PR would add the Sophie language to the projects list.
> Add Sophie language entry

- _data/projects.yml
I didn't mention FuncSug main feature
> Changed the summary of FuncSug language

- _data/projects.yml
- _data/tags.yml
This PR adds tags to Cella. It also adds some other tags not used by Cella that will be useful for other programming languages.
> Add tags to Cella

- _data/projects.yml
The commit message says "type" instead of "typo" so please ignore that lmao xD
> Corrected typo in author.name under Sphere Language

- _data/projects.yml
> Livenaming my project

- _data/projects.yml
I have moved development from Github to Codeberg.
> update source and author for Core

- _data/projects.yml
> Fix jank's logo image

- index.html
This should fix the inactive categorization.
> Fix the inactive categorization to actually work

- BUILD.md
Since I got initially somewhat lost while trying to build the website locally, I thought it might be a good idea to document what I did to get it running. I hope others find this useful. If anybody finds an error with these steps, please feel free to correct them.
> Add a file with some basic instructions on how to build the website

- css/style.css
- index.html
- static/filter.js
This adds a new tag summary field that shows up whenever any tag(s) with a description are selected:
> Add JavaScript handling to actually show the tag descriptions

- _data/projects.yml
> Update projects.yml with Admiran description

- Gemfile
- Gemfile.lock
I needed to do these gem file changes to build the website locally. Should these be added back to the repository, or is it best left alone?
@jamestmartin perhaps you would know?
> Add perhaps necessary(?) changes to gem file
